services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 2s
      timeout: 3s
      retries: 5
    
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "80:8978"
    environment:
      - CB_SERVER_PORT=8978
    volumes:
      - dbeaver-data:/opt/cloudbeaver/workspace
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
  dbeaver-data: